import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Privacy Policy — Rush In Documentation Center',
  description:
    'How Rush In Documentation Center collects, uses and protects your personal information.',
};

const h2: React.CSSProperties = { fontFamily: "'Ubuntu', sans-serif", fontSize: 24, fontWeight: 700, color: '#1D2540', margin: '40px 0 0' };
const h3: React.CSSProperties = { fontFamily: "'Ubuntu', sans-serif", fontSize: 18, fontWeight: 700, color: '#283778', margin: '26px 0 0' };
const p: React.CSSProperties = { fontSize: 15, lineHeight: 1.75, color: '#47506B', margin: '12px 0 0' };
const ul: React.CSSProperties = { margin: '12px 0 0', paddingLeft: 22, color: '#47506B', fontSize: 15, lineHeight: 1.75 };
const term: React.CSSProperties = { color: '#1D2540', fontWeight: 700 };

function P({ children }: { children: React.ReactNode }) {
  return <p style={p}>{children}</p>;
}

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main>
        {/* Header band */}
        <section style={{ background: 'linear-gradient(180deg, #F6F8FC 0%, #FFFFFF 100%)', borderBottom: '1px solid #EEF1F8' }}>
          <div style={{ maxWidth: 860, margin: '0 auto', padding: '56px 24px 44px' }}>
            <a href="/#top" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 13.5, fontWeight: 700, color: '#283778' }}>← Back to home</a>
            <h1 className="font-ub" style={{ fontSize: 'clamp(30px, 4vw, 44px)', fontWeight: 700, color: '#1D2540', margin: '18px 0 0', letterSpacing: '-0.01em' }}>Privacy Policy</h1>
            <div style={{ fontSize: 13.5, color: '#8A91A8', marginTop: 12, fontWeight: 600 }}>Last updated: August 15, 2025</div>
          </div>
        </section>

        <article style={{ maxWidth: 860, margin: '0 auto', padding: '10px 24px 80px' }}>
          <P>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</P>
          <P>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</P>

          <h2 style={h2}>Interpretation and Definitions</h2>
          <h3 style={h3}>Interpretation</h3>
          <P>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</P>

          <h3 style={h3}>Definitions</h3>
          <P>For the purposes of this Privacy Policy:</P>
          <ul style={ul}>
            <li><span style={term}>Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><span style={term}>Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><span style={term}>Company</span> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Rush In Documentation Center, 7869 Santa Monica Blvd. West Hollywood CA 90046.</li>
            <li><span style={term}>Cookies</span> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website, among its many uses.</li>
            <li><span style={term}>Country</span> refers to: California, United States</li>
            <li><span style={term}>Device</span> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
            <li><span style={term}>Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
            <li><span style={term}>Service</span> refers to the Website.</li>
            <li><span style={term}>Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
            <li><span style={term}>Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><span style={term}>Website</span> refers to Rush In Documentation Center, accessible from <a href="https://rushindocumentation.com/" target="_blank" rel="noopener" style={{ color: '#283778', fontWeight: 600 }}>https://rushindocumentation.com/</a></li>
            <li><span style={term}>You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 style={h2}>Collecting and Using Your Personal Data</h2>
          <h3 style={h3}>Types of Data Collected</h3>
          <P><span style={term}>Personal Data.</span> While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</P>
          <ul style={ul}>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h3 style={h3}>Usage Data</h3>
          <P>Usage Data is collected automatically when using the Service.</P>
          <P>Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</P>
          <P>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</P>
          <P>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</P>

          <h3 style={h3}>Tracking Technologies and Cookies</h3>
          <P>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</P>
          <ul style={ul}>
            <li><span style={term}>Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser settings so that it will refuse Cookies, our Service may use Cookies.</li>
            <li><span style={term}>Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
          </ul>
          <P>Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. We use both Session and Persistent Cookies for the purposes set out below:</P>
          <P><span style={term}>Necessary / Essential Cookies</span> — Type: Session Cookies; Administered by: Us. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</P>
          <P><span style={term}>Cookies Policy / Notice Acceptance Cookies</span> — Type: Persistent Cookies; Administered by: Us. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</P>
          <P><span style={term}>Functionality Cookies</span> — Type: Persistent Cookies; Administered by: Us. Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</P>

          <h2 style={h2}>Use of Your Personal Data</h2>
          <P>The Company may use Personal Data for the following purposes:</P>
          <ul style={ul}>
            <li><span style={term}>To provide and maintain our Service,</span> including to monitor the usage of our Service.</li>
            <li><span style={term}>To manage Your Account:</span> to manage Your registration as a user of the Service.</li>
            <li><span style={term}>For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><span style={term}>To contact You:</span> by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
            <li><span style={term}>To provide You with news, special offers and general information</span> about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
            <li><span style={term}>To manage Your requests:</span> To attend to and manage Your requests to Us.</li>
            <li><span style={term}>For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><span style={term}>For other purposes:</span> such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
          </ul>
          <P>We may share Your personal information in the following situations: with Service Providers; for business transfers; with Affiliates; with business partners; with other users (when You share personal information in public areas); and with Your consent.</P>

          <h2 style={h2}>Retention of Your Personal Data</h2>
          <P>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</P>

          <h2 style={h2}>Transfer of Your Personal Data</h2>
          <P>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of Your jurisdiction where the data protection laws may differ. Your consent to this Privacy Policy, followed by Your submission of such information, represents Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</P>

          <h2 style={h2}>Delete Your Personal Data</h2>
          <P>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, or by contacting Us to request access to, correct, or delete any personal information that You have provided to Us. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</P>

          <h2 style={h2}>Disclosure of Your Personal Data</h2>
          <h3 style={h3}>Business Transactions</h3>
          <P>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</P>
          <h3 style={h3}>Law enforcement</h3>
          <P>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</P>
          <h3 style={h3}>Other legal requirements</h3>
          <P>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: comply with a legal obligation; protect and defend the rights or property of the Company; prevent or investigate possible wrongdoing in connection with the Service; protect the personal safety of Users of the Service or the public; and protect against legal liability.</P>

          <h2 style={h2}>Security of Your Personal Data</h2>
          <P>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</P>

          <h2 style={h2}>Children’s Privacy</h2>
          <P>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</P>

          <h2 style={h2}>Links to Other Websites</h2>
          <P>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</P>

          <h2 style={h2}>Changes to this Privacy Policy</h2>
          <P>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the “Last updated” date. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</P>

          <h2 style={h2}>Contact Us</h2>
          <P>If you have any questions about this Privacy Policy, You can contact us by visiting{' '}
            <a href="https://rushindocumentation.com/contact/" target="_blank" rel="noopener" style={{ color: '#283778', fontWeight: 600 }}>this page</a> on our website, or call{' '}
            <a href="tel:+13236451600" style={{ color: '#283778', fontWeight: 700 }}>+1 323 645 1600</a>.
          </P>
        </article>
      </main>
      <Footer />
    </>
  );
}
